atelier-2019-04-08.html : atelier-2019-04-08.md
	pandoc -f markdown -t slidy -i -s --self-contained --highlight-style pygments -s atelier-2019-04-08.md -o atelier-2019-04-08.html 

conflation.html : conflation.md
	pandoc -f markdown -t slidy -i -s --self-contained --highlight-style pygments -s conflation.md -o conflation.html 


test.html : test.md
	pandoc -f markdown -t slidy -i -s --self-contained -s test.md -o test.html 



