conflation.html : conflation.md
	pandoc -f markdown -t slidy -i -s --self-contained --highlight-style pygments -s conflation.md -o conflation.html 


test.html : test.md
	pandoc -f markdown -t slidy -i -s --self-contained -s test.md -o test.html 
